DROP TABLE IF EXISTS Countries CASCADE;

CREATE TABLE IF NOT EXISTS Countries (
    code VARCHAR PRIMARY KEY,
    name VARCHAR,
    continentName VARCHAR
);

INSERT INTO Countries(code, name) VALUES
('BR','Brazil'),
('CN','China'),
('RU','Russia'),
('ID','Indonesia'),
('AL','Albania'),
('VE','Venezuela'),
('IE','Ireland'),
('PL','Poland'),
('HN','Honduras'),
('PH','Philippines'),
('KZ','Kazakhstan'),
('AR','Argentina'),
('CA','Canada'),
('CZ','Czech Republic'),
('JP','Japan'),
('NG','Nigeria'),
('SE','Sweden'),
('LY','Libya'),
('MN','Mongolia'),
('MZ','Mozambique'),
('FR','France'),
('MX','Mexico'),
('NP','Nepal'),
('TZ','Tanzania'),
('GQ','Equatorial Guinea'),
('CL','Chile'),
('RS','Serbia'),
('MY','Malaysia'),
('IR','Iran'),
('UA','Ukraine'),
('PT','Portugal'),
('US','United States'),
('JO','Jordan'),
('PA','Panama'),
('CF','Central African Republic'),
('AF','Afghanistan'),
('PY','Paraguay'),
('GR','Greece'),
('MG','Madagascar'),
('VN','Vietnam'),
('AM','Armenia'),
('GT','Guatemala'),
('BO','Bolivia'),
('DE','Germany'),
('BA','Bosnia and Herzegovina'),
('BY','Belarus'),
('PE','Peru'),
('CO','Colombia'),
('MM','Myanmar'),
('GB','United Kingdom'),
('YE','Yemen'),
('GE','Georgia'),
('NO','Norway'),
('AZ','Azerbaijan'),
('BT','Bhutan'),
('TH','Thailand'),
('IT','Italy'),
('CD','Democratic Republic of the Congo'),
('SI','Slovenia'),
('AU','Australia'),
('MW','Malawi'),
('NL','Netherlands'),
('UG','Uganda'),
('PW','Palau'),
('FI','Finland'),
('BD','Bangladesh'),
('CU','Cuba'),
('PK','Pakistan'),
('BE','Belgium'),
('TL','East Timor'),
('DM','Dominica'),
('BJ','Benin'),
('UY','Uruguay'),
('SA','Saudi Arabia'),
('ZA','South Africa'),
('QA','Qatar'),
('KG','Kyrgyzstan'),
('PS','Palestinian Territory'),
('CR','Costa Rica'),
('AD','Andorra'),
('HU','Hungary'),
('FM','Micronesia'),
('HR','Croatia'),
('DK','Denmark'),
('NE','Niger'),
('AS','American Samoa'),
('BG','Bulgaria'),
('EG','Egypt'),
('TN','Tunisia'),
('KY','Cayman Islands'),
('CM','Cameroon'),
('LK','Sri Lanka'),
('KE','Kenya'),
('BF','Burkina Faso'),
('BH','Bahrain'),
('KR','South Korea'),
('NC','New Caledonia'),
('GN','Guinea'),
('MD','Moldova'),
('PF','French Polynesia'),
('LU','Luxembourg'),
('KH','Cambodia'),
('AE','United Arab Emirates'),
('LV','Latvia'),
('DO','Dominican Republic'),
('BW','Botswana'),
('WS','Samoa'),
('MU','Mauritius'),
('HK','Hong Kong'),
('MK','Macedonia'),
('LA','Laos'),
('EC','Ecuador'),
('SY','Syria'),
('HT','Haiti'),
('KP','North Korea'),
('ES','Spain'),
('LB','Lebanon'),
('GW','Guinea-Bissau'),
('TM','Turkmenistan'),
('ZW','Zimbabwe'),
('ML', 'Mali'),
('NI', 'Nicaragua'),
('ET', 'Ethiopia'),
('IQ', 'Iraq'),
('KM', 'Comors');